# Examples and Exercises from Think Stats, 2nd Edition

http://thinkstats2.com

Copyright 2016 Allen B. Downey

MIT License: https://opensource.org/licenses/MIT


In [2]:
!git clone https://github.com/sssoyeonss/ThinkStats2


Cloning into 'ThinkStats2'...
remote: Enumerating objects: 2826, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 2826 (delta 0), reused 4 (delta 0), pack-reused 2821
Receiving objects: 100% (2826/2826), 172.42 MiB | 24.39 MiB/s, done.
Resolving deltas: 100% (1609/1609), done.
Checking out files: 100% (485/485), done.


In [6]:
!pwd

/content


In [9]:
!ls

sample_data  ThinkStats2


In [10]:
%cd ThinkStats2

/content/ThinkStats2


In [12]:
%cd code

/content/ThinkStats2/code


In [13]:
!python nsfg.py

(13593, 244)
All tests passed.


In [14]:
from __future__ import print_function, division

import nsfg

## Examples from Chapter 1

Read NSFG data into a Pandas DataFrame.

In [15]:
preg = nsfg.ReadFemPreg()
preg.head()

caseid  pregordr  howpreg_n  howpreg_p  ...  secu_p  sest  cmintvw  totalwgt_lb
0       1         1        NaN        NaN  ...       2     9      NaN       8.8125
1       1         2        NaN        NaN  ...       2     9      NaN       7.8750
2       2         1        NaN        NaN  ...       2    12      NaN       9.1250
3       2         2        NaN        NaN  ...       2    12      NaN       7.0000
4       2         3        NaN        NaN  ...       2    12      NaN       6.1875

[5 rows x 244 columns]

Print the column names.

In [16]:
preg.columns

Index(['caseid', 'pregordr', 'howpreg_n', 'howpreg_p', 'moscurrp', 'nowprgdk',
       'pregend1', 'pregend2', 'nbrnaliv', 'multbrth',
       ...
       'laborfor_i', 'religion_i', 'metro_i', 'basewgt', 'adj_mod_basewgt',
       'finalwgt', 'secu_p', 'sest', 'cmintvw', 'totalwgt_lb'],
      dtype='object', length=244)

Select a single column name.

In [17]:
preg.columns[1]

'pregordr'

Select a column and check what type it is.

In [18]:
pregordr = preg['pregordr']
type(pregordr)

pandas.core.series.Series

Print a column.

In [ ]:
pregordr

Select a single element from a column.

In [19]:
pregordr[0]

1

Select a slice from a column.

In [ ]:
pregordr[2:5]

2    1
3    2
4    3
Name: pregordr, dtype: int64

Select a column using dot notation.

In [20]:
pregordr = preg.pregordr

Count the number of times each value occurs.

In [21]:
preg.outcome.value_counts().sort_index()

1    9148
2    1862
3     120
4    1921
5     190
6     352
Name: outcome, dtype: int64

Check the values of another variable.

In [22]:
preg.birthwgt_lb.value_counts().sort_index()

0.0        8
1.0       40
2.0       53
3.0       98
4.0      229
5.0      697
6.0     2223
7.0     3049
8.0     1889
9.0      623
10.0     132
11.0      26
12.0      10
13.0       3
14.0       3
15.0       1
Name: birthwgt_lb, dtype: int64

Make a dictionary that maps from each respondent's `caseid` to a list of indices into the pregnancy `DataFrame`.  Use it to select the pregnancy outcomes for a single respondent.

In [24]:
caseid = 1
preg_map = nsfg.MakePregMap(preg)
indices = preg_map[caseid]
preg.outcome[indices].values

array([1, 1])

## Exercises

Select the `birthord` column, print the value counts, and compare to results published in the [codebook](http://www.icpsr.umich.edu/nsfg6/Controller?displayPage=labelDetails&fileCode=PREG&section=A&subSec=8016&srtLabel=611933)

In [27]:
# Solution goes here
preg.birthord.value_counts().sort_index()

1.0     4413
2.0     2874
3.0     1234
4.0      421
5.0      126
6.0       50
7.0       20
8.0        7
9.0        2
10.0       1
Name: birthord, dtype: int64

We can also use `isnull` to count the number of nans.

In [28]:
preg.birthord.isnull().sum()

4445

Select the `prglngth` column, print the value counts, and compare to results published in the [codebook](http://www.icpsr.umich.edu/nsfg6/Controller?displayPage=labelDetails&fileCode=PREG&section=A&subSec=8016&srtLabel=611931)

In [29]:
# Solution goes here
preg.prglngth.value_counts()

39    4744
40    1120
38     609
9      594
41     591
6      543
37     457
13     446
4      412
8      409
35     357
36     329
42     328
17     253
11     202
30     198
5      181
7      175
12     170
3      151
43     148
22     147
10     137
32     122
26     117
2       78
34      60
33      50
44      46
16      44
15      39
28      38
21      37
19      34
24      31
31      29
14      29
29      23
20      18
18      17
0       15
25      15
23      12
45      10
1        9
27       8
48       7
50       2
46       1
47       1
Name: prglngth, dtype: int64

To compute the mean of a column, you can invoke the `mean` method on a Series.  For example, here is the mean birthweight in pounds:

In [30]:
preg.totalwgt_lb.mean()

7.265628457623368

Create a new column named <tt>totalwgt_kg</tt> that contains birth weight in kilograms.  Compute its mean.  Remember that when you create a new column, you have to use dictionary syntax, not dot notation.

In [31]:
# Solution goes here
preg['totalwgt_kg'] = preg['totalwgt_lb'] / 2.2
preg['totalwgt_kg'].mean()

3.302558389828807

`nsfg.py` also provides `ReadFemResp`, which reads the female respondents file and returns a `DataFrame`:

In [32]:
resp = nsfg.ReadFemResp()

`DataFrame` provides a method `head` that displays the first five rows:

In [33]:
resp.head()

caseid  rscrinf  rdormres  ...  cmlstyr  screentime   intvlngth
0    2298        1         5  ...     1222    18:26:36  110.492667
1    5012        1         5  ...     1221    16:30:59   64.294000
2   11586        1         5  ...     1222    18:19:09   75.149167
3    6794        5         5  ...     1222    15:54:43   28.642833
4     616        1         5  ...     1221    14:19:44   69.502667

[5 rows x 3087 columns]

Select the `age_r` column from `resp` and print the value counts.  How old are the youngest and oldest respondents?

In [34]:
# Solution goes here
resp.age_r.value_counts().sort_index()

15    217
16    223
17    234
18    235
19    241
20    258
21    267
22    287
23    282
24    269
25    267
26    260
27    255
28    252
29    262
30    292
31    278
32    273
33    257
34    255
35    262
36    266
37    271
38    256
39    215
40    256
41    250
42    215
43    253
44    235
Name: age_r, dtype: int64

We can use the `caseid` to match up rows from `resp` and `preg`.  For example, we can select the row from `resp` for `caseid` 2298 like this:

In [35]:
resp[resp.caseid==2298]

caseid  rscrinf  rdormres  ...  cmlstyr  screentime   intvlngth
0    2298        1         5  ...     1222    18:26:36  110.492667

[1 rows x 3087 columns]

And we can get the corresponding rows from `preg` like this:

In [36]:
preg[preg.caseid==2298]

caseid  pregordr  howpreg_n  ...  cmintvw  totalwgt_lb  totalwgt_kg
2610    2298         1        NaN  ...      NaN       6.8750     3.125000
2611    2298         2        NaN  ...      NaN       5.5000     2.500000
2612    2298         3        NaN  ...      NaN       4.1875     1.903409
2613    2298         4        NaN  ...      NaN       6.8750     3.125000

[4 rows x 245 columns]

How old is the respondent with `caseid` 1?

In [37]:
# Solution goes here
resp[resp.caseid==1]

caseid  rscrinf  rdormres  ...  cmlstyr  screentime  intvlngth
1069       1        1         5  ...     1219    19:56:43  67.563833

[1 rows x 3087 columns]

What are the pregnancy lengths for the respondent with `caseid` 2298?

In [39]:
# Solution goes here
preg[preg.caseid==2298].prglngth

2610    40
2611    36
2612    30
2613    40
Name: prglngth, dtype: int64

What was the birthweight of the first baby born to the respondent with `caseid` 5012?

In [40]:
# Solution goes here
preg[preg.caseid==5012].totalwgt_lb

5515    6.0
Name: totalwgt_lb, dtype: float64